#pragma once
#undef RGBLIGHT_ANIMATIONS

#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_STATIC_GRADIENT

/* VIAL Specific definitions */
#define VIAL_KEYBOARD_UID {0x9D, 0x69, 0x43, 0x11, 0x7A, 0x22, 0xE7, 0x0B}
#define VIAL_INSECURE = yes